"""
NetPulse — Platform-Native Cron Ingestion Script
This script is designed to be executed by a platform native cron job (e.g., Railway Cron)
to batch ingest BGP, Topology, and Latency measurements without running a custom orchestrator.

Usage:
  python scripts/run_ingestion.py
"""

import asyncio
import structlog
from typing import Optional
from sqlalchemy.ext.asyncio import AsyncSession
from app.db.models.base import get_session
from app.core.config import get_settings
from app.core.logging import setup_logging

# Ingestion Clients
from app.ingestion.ripe_atlas_client import RipeAtlasClient
from app.ingestion.routeviews_client import RouteViewsClient
from app.ingestion.caida_loader import CaidaLoader
from app.db.repositories.measurement_repo import MeasurementRepository
from app.db.repositories.bgp_repo import BGPRepository

logger = structlog.get_logger()

async def run_caida_ingestion(session: AsyncSession):
    """Run daily CAIDA topology ingestion."""
    logger.info("ingestion_cron_start", source="caida")
    loader = CaidaLoader(session)
    await loader.load_as_relationships()
    logger.info("ingestion_cron_end", source="caida")

async def run_routeviews_ingestion(session: AsyncSession):
    """Run RouteViews BGP update ingestion."""
    logger.info("ingestion_cron_start", source="routeviews")
    # Using the dependency injected in the repository
    repo = BGPRepository(session)
    client = RouteViewsClient(repo)
    # Fetch latest BGP updates
    await client.poll_updates()
    logger.info("ingestion_cron_end", source="routeviews")

async def run_atlas_ingestion(session: AsyncSession):
    """Run RIPE Atlas measurement ingestion."""
    logger.info("ingestion_cron_start", source="ripe_atlas")
    repo = MeasurementRepository(session)
    client = RipeAtlasClient(repo)
    # Define probes we want to update measurements for
    # In a full deployment, this list would be generated by querying the probes table
    # For now we use the test anchor
    TEST_ANCHOR_PROBE_ID = 10001
    await client.get_measurement_results(TEST_ANCHOR_PROBE_ID)
    logger.info("ingestion_cron_end", source="ripe_atlas")

async def main():
    settings = get_settings()
    setup_logging(settings.log_level)
    logger.info("starting_scheduled_ingestion")
    
    async for session in get_session():
        try:
            # We run CAIDA first to ensure topology is fresh
            await run_caida_ingestion(session)
            
            # Run RouteViews and Atlas concurrently
            await asyncio.gather(
                run_routeviews_ingestion(session),
                run_atlas_ingestion(session)
            )
            logger.info("scheduled_ingestion_completed_successfully")
        except Exception as e:
            logger.error("scheduled_ingestion_failed", error=str(e))
            raise

if __name__ == "__main__":
    asyncio.run(main())
